name: 'Submit to Web Store'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies and build extension
        run: |
          cd apps/browser-extension
          pnpm i
          pnpm plasmo build --zip
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-extension-artifact
          path: apps/browser-extension/build/chrome-mv3-prod.zip
